export default defineEventHandler(() => {
  const templates = [
    {
      id: 'tpl-001',
      name: '浪漫粉金',
      preview: 'linear-gradient(135deg, #f6d365 0%, #fda085 100%)',
      pages: [
        {
          name: '封面',
          backgroundColor: '#fff5f7',
          elements: [
            {
              type: 'text',
              subType: 'title',
              x: 40,
              y: 220,
              width: 240,
              height: 44,
              text: '我们的婚礼',
              fontSize: 34,
              textAlign: 'center',
              textColor: '#8a3a4a',
              fontFamily: 'Microsoft YaHei',
              locked: false,
              visible: true,
            },
            {
              type: 'text',
              subType: 'subtitle',
              x: 80,
              y: 280,
              width: 160,
              height: 28,
              text: 'Wedding Day',
              fontSize: 20,
              textAlign: 'center',
              textColor: '#c97b8a',
              fontFamily: 'Microsoft YaHei',
              locked: false,
              visible: true,
            },
          ],
        },
        {
          name: '内页',
          backgroundColor: '#fff0f3',
          elements: [
            {
              type: 'text',
              subType: 'subtitle',
              x: 60,
              y: 100,
              width: 200,
              height: 28,
              text: '诚挚邀请您',
              fontSize: 20,
              textAlign: 'center',
              textColor: '#8a3a4a',
              fontFamily: 'Microsoft YaHei',
              locked: false,
              visible: true,
            },
          ],
        },
      ],
    },
    {
      id: 'tpl-002',
      name: '经典蓝紫',
      preview: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      pages: [
        {
          name: '封面',
          backgroundColor: '#f5f3ff',
          elements: [
            {
              type: 'text',
              subType: 'title',
              x: 40,
              y: 230,
              width: 240,
              height: 44,
              text: 'Our Wedding',
              fontSize: 32,
              textAlign: 'center',
              textColor: '#4c1d95',
              fontFamily: 'Microsoft YaHei',
              locked: false,
              visible: true,
            },
          ],
        },
      ],
    },
    {
      id: 'tpl-003',
      name: '梦幻红粉',
      preview: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
      pages: [
        {
          name: '封面',
          backgroundColor: '#fff1f2',
          elements: [
            {
              type: 'text',
              subType: 'title',
              x: 60,
              y: 220,
              width: 200,
              height: 44,
              text: '请 柬',
              fontSize: 34,
              textAlign: 'center',
              textColor: '#be185d',
              fontFamily: 'Microsoft YaHei',
              locked: false,
              visible: true,
            },
          ],
        },
      ],
    },
    {
      id: 'tpl-004',
      name: '中式喜红',
      preview: 'linear-gradient(135deg, #c9184a 0%, #800f2f 100%)',
      pages: [
        {
          name: '封面',
          backgroundColor: '#fff5f5',
          elements: [
            {
              type: 'text',
              subType: 'title',
              x: 60,
              y: 200,
              width: 200,
              height: 60,
              text: '囍',
              fontSize: 72,
              textAlign: 'center',
              textColor: '#8a0e22',
              fontFamily: 'Microsoft YaHei',
              locked: false,
              visible: true,
            },
            {
              type: 'text',
              subType: 'subtitle',
              x: 60,
              y: 300,
              width: 200,
              height: 24,
              text: '百年好合',
              fontSize: 20,
              textAlign: 'center',
              textColor: '#8a0e22',
              fontFamily: 'Microsoft YaHei',
              locked: false,
              visible: true,
            },
          ],
        },
      ],
    },
    {
      id: 'tpl-005',
      name: '清新薄荷',
      preview: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
      pages: [
        {
          name: '封面',
          backgroundColor: '#f0fdfa',
          elements: [
            {
              type: 'text',
              subType: 'title',
              x: 60,
              y: 230,
              width: 200,
              height: 40,
              text: 'Wedding',
              fontSize: 30,
              textAlign: 'center',
              textColor: '#0f766e',
              fontFamily: 'Microsoft YaHei',
              locked: false,
              visible: true,
            },
          ],
        },
      ],
    },
    {
      id: 'tpl-006',
      name: '金色典雅',
      preview: 'linear-gradient(135deg, #f5af19 0%, #f12711 100%)',
      pages: [
        {
          name: '封面',
          backgroundColor: '#fffbeb',
          elements: [
            {
              type: 'text',
              subType: 'title',
              x: 60,
              y: 230,
              width: 200,
              height: 44,
              text: 'Golden Love',
              fontSize: 30,
              textAlign: 'center',
              textColor: '#b45309',
              fontFamily: 'Microsoft YaHei',
              locked: false,
              visible: true,
            },
          ],
        },
      ],
    },
  ];
  return {
    code: 0,
    message: 'ok',
    data: templates,
  };
});
